/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.100
 * Generated at: 2024-06-03 23:42:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cadastroEvento_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"styleCriaEvento.css\">\n");
      out.write("\n");
      out.write("        <title>Cadastro de Eventos</title>\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("        ");
  // recebe dados do usuario de outra pagina
            String u = request.getParameter("email");
            String emailIndex = "index.jsp?email=" + u;
        
      out.write("\n");
      out.write("        <header>\n");
      out.write("            <!--logo-->\n");
      out.write("            <a href=\"");
      out.print(emailIndex);
      out.write("\" class=\"logo\"> Diver<br />Ticket<br /> </a>\n");
      out.write("            <!--botoes header-->\n");
      out.write("        </header>\n");
      out.write("        <main>\n");
      out.write("            <form id=\"eventoForm\" action=\"salvarEvento.jsp\" method=\"post\" onsubmit=\"return cadastrarEvento()\">\n");
      out.write("\n");
      out.write("                <div class=\"conteudo\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <label for=\"nomeDoevento\"><b>Nome Do Evento</b></label>\n");
      out.write("                    <input type=\"text\" placeholder=\"Insira o nome do evento\" name=\"nomeDoevento\" id=\"nomeDoevento\" required><br><br>\n");
      out.write("\n");
      out.write("                    <label for=\"local\"><b>Local</b></label>\n");
      out.write("                    <input type=\"text\" placeholder=\"Insira o local\" name=\"local\" id=\"local\" required><br><br>\n");
      out.write("\n");
      out.write("                    <label for=\"endereco\">Endereço</label>\n");
      out.write("                    <input type=\"text\" placeholder=\"Insira o Endereço\" name=\"endereco\" id=\"endereco\" required><br><br>\n");
      out.write("\n");
      out.write("                    <label for=\"cep\">CEP</label>\n");
      out.write("                    <input type=\"text\" placeholder=\"Insira o CEP\" name=\"cep\" id=\"cep\" required><br><br>\n");
      out.write("\n");
      out.write("                    <label for=\"imagem\">Imagem do Evento:</label>\n");
      out.write("                    <input type=\"file\" id=\"fileInput\" name=\"fileInput\"><br><br>\n");
      out.write("\n");
      out.write("                    <label for=\"descricao\">Descrição do Evento:</label>\n");
      out.write("                    <textarea id=\"descricao\" placeholder=\"Escreva aqui\" name=\"descricao\" rows=\"4\"></textarea><br><br>\n");
      out.write("\n");
      out.write("                    <label for=\"dataInicio\">Data de Início:</label>\n");
      out.write("                    <input type=\"date\" id=\"dataInicio\" name=\"dataInicio\" required><br><br>\n");
      out.write("\n");
      out.write("                    <label for=\"dataFim\">Data de Fim:</label>\n");
      out.write("                    <input type=\"date\" id=\"dataFim\" name=\"dataFim\" required><br><br>\n");
      out.write("\n");
      out.write("                    <label for=\"horaInicio\">Hora de Início:</label>\n");
      out.write("                    <input type=\"time\" id=\"horaInicio\" name=\"horaInicio\" required><br><br>\n");
      out.write("\n");
      out.write("                    <label for=\"horaFim\">Hora de Fim:</label>\n");
      out.write("                    <input type=\"time\" id=\"horaFim\" name=\"horaFim\" required><br><br>\n");
      out.write("\n");
      out.write("                    <label for=\"categoria\">Categoria de Evento:</label>\n");
      out.write("                    <select id=\"categoria\" name=\"categoria\">\n");
      out.write("                        <option value=\"\">Selecione...</option>\n");
      out.write("                        <option value=\"festa e show\">Festa e Show</option>\n");
      out.write("                        <option value=\"teatro\">Teatro</option>\n");
      out.write("                        <option value=\"palestra\">Palestra</option>\n");
      out.write("                        <option value=\"stand up comedy\">Stand up comedy</option>\n");
      out.write("                        <option value=\"esporte\">Esporte</option>\n");
      out.write("                        <option value=\"gastronomia\">Gastronomia</option>\n");
      out.write("                        <option value=\"passeios\">Passeios</option>\n");
      out.write("                        <option value=\"infantil\">Infantil</option>\n");
      out.write("                    </select><br><br>\n");
      out.write("\n");
      out.write("                    <!-- =========================================================== -->\n");
      out.write("\n");
      out.write("                    <div class=\"tipoIngresso\">\n");
      out.write("                        <label >Tipo de Ingresso:</label>\n");
      out.write("                        <input class=\"checkbox\" type=\"checkbox\" id=\"vip\" name=\"vip\" value=\"1\">\n");
      out.write("                        <label class=\"labelTipoIngresso\" for=\"vip\"> Vip</label>\n");
      out.write("                        <input class=\"checkbox\" type=\"checkbox\" id=\"meia\" name=\"meia\" value=\"2\">\n");
      out.write("                        <label class=\"labelTipoIngresso\" for=\"meia\"> Meia</label>\n");
      out.write("                        <input class=\"checkbox\" type=\"checkbox\" id=\"inteira\" name=\"inteira\" value=\"3\">\n");
      out.write("                        <label class=\"labelTipoIngresso\" for=\"inteira\">Inteira </label>\n");
      out.write("                        <button type=\"button\" class=\"inputTipoIngresso\" onclick=\"criarIngresso()\">Criar ingresso</button>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <div class=\"inserirIngressos\" id=\"inserirIngressos\">\n");
      out.write("                        <!--=================== vip===================== -->\n");
      out.write("                        <div id=\"divVip\">\n");
      out.write("                            <p id=\"tituloVip\">Ingresso Vip</p>\n");
      out.write("\n");
      out.write("                            <label for=\"qtdingressoVip\">Quantidade de <br>Ingresso:</label>\n");
      out.write("                            <input type=\"number\" id=\"qtdingressoVip\" name=\"qtdingressoVip\" style=\"width: 130px;\" value=\"0\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <label for=\"precoVip\">Preço:</label>\n");
      out.write("                            <input type=\"number\" name=\"precoVip\" id=\"precoVip\" style=\"width: 130px;\" value=\"0\"><br>\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div id=\"divMeia\">\n");
      out.write("                            <!--=================== meia ===================== -->\n");
      out.write("                            <p id=\"tituloMeia\">Ingresso Meia</p>\n");
      out.write("\n");
      out.write("                            <label for=\"qtdingressoMeia\">Quantidade de <br>Ingresso:</label>\n");
      out.write("                            <input type=\"number\" id=\"qtdingressoMeia\" name=\"qtdingressoMeia\" style=\"width: 130px;\" value=\"0\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <label for=\"precoMeia\">Preço:</label>\n");
      out.write("                            <input type=\"number\" name=\"precoMeia\" id=\"precoMeia\" style=\"width: 130px;\" value=\"0\"><br>\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                        <div id=\"divInteiro\">\n");
      out.write("                            <!--=================== inteira ===================== -->\n");
      out.write("                            <p id=\"tituloInteiro\">Ingresso Inteira</p>\n");
      out.write("\n");
      out.write("                            <label for=\"qtdingressoInteira\">Quantidade de <br>Ingresso:</label>\n");
      out.write("                            <input type=\"number\" id=\"qtdingressoInteira\" name=\"qtdingressoInteira\" style=\"width: 130px;\" value=\"0\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <label for=\"precoInteiro\">Preço:</label>\n");
      out.write("                            <input type=\"number\" name=\"precoInteiro\" id=\"precoInteiro\" style=\"width: 130px;\" value=\"0\"><br>\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div style=\"display: none;\">\n");
      out.write("                        <input type=\"text\" name=\"email\" id=\"email\" value=\"");
      out.print( u);
      out.write("\">\n");
      out.write("                        <input type=\"text\" id=\"fileNameInput\" name=\"fileNameInput\" />\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <!-- ======================================================================================== -->\n");
      out.write("                    <button type=\"submit\">Publicar Evento</button>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            </form>\n");
      out.write("        </main>\n");
      out.write("        <script>\n");
      out.write("\n");
      out.write("            /*  pegar o nome do arquivo da imagem   */\n");
      out.write("            const fileInput = document.getElementById('fileInput');\n");
      out.write("            const fileNameInput = document.getElementById('fileNameInput');\n");
      out.write("\n");
      out.write("            fileInput.addEventListener('change', () => {\n");
      out.write("                const fileName = fileInput.files[0].name;\n");
      out.write("                fileNameInput.value = fileName;\n");
      out.write("            });\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            /*============================criar ingresso===================================*/\n");
      out.write("\n");
      out.write("            const inputVip = document.getElementById(\"vip\");\n");
      out.write("            const inputMeia = document.getElementById(\"meia\");\n");
      out.write("            const inputInteira = document.getElementById(\"inteira\");\n");
      out.write("            const divVip = document.getElementById(\"divVip\");\n");
      out.write("            const qtdingressoVip = document.getElementById(\"qtdingressoVip\");\n");
      out.write("            const precoVip = document.getElementById(\"precoVip\");\n");
      out.write("            const divMeia = document.getElementById(\"divMeia\");\n");
      out.write("            const qtdingressoMeia = document.getElementById(\"qtdingressoMeia\");\n");
      out.write("            const precoMeia = document.getElementById(\"precoMeia\");\n");
      out.write("            const divInteiro = document.getElementById(\"divInteiro\");\n");
      out.write("            const qtdingressoInteira = document.getElementById(\"qtdingressoInteiro\");\n");
      out.write("            const precoInteiro = document.getElementById(\"precoInteiro\");\n");
      out.write("\n");
      out.write("\n");
      out.write("            //função para mostrar apenas o ingresso que ele escolher a partir do input radio\n");
      out.write("            function criarIngresso() {\n");
      out.write("\n");
      out.write("                let vip = inputVip.checked;\n");
      out.write("                let meia = inputMeia.checked;\n");
      out.write("                let inteiro = inputInteira.checked;\n");
      out.write("                divVip.style.display = \"none\";\n");
      out.write("                divMeia.style.display = \"none\";\n");
      out.write("                divInteiro.style.display = \"none\";\n");
      out.write("                if (vip === false && meia === false && inteiro === false) {\n");
      out.write("                    alert(\"ingresso Não Cadastrado\");\n");
      out.write("                }\n");
      out.write("                if (vip === true) {\n");
      out.write("                    divVip.style.display = \"block\";\n");
      out.write("                }\n");
      out.write("                if (meia === true) {\n");
      out.write("                    divMeia.style.display = \"block\";\n");
      out.write("                }\n");
      out.write("                if (inteiro === true) {\n");
      out.write("                    divInteiro.style.display = \"block\";\n");
      out.write("                }\n");
      out.write("\n");
      out.write("            }\n");
      out.write("            /*======================================================================*/\n");
      out.write("\n");
      out.write("            /*=============================publicar evento==================================*/\n");
      out.write("\n");
      out.write("\n");
      out.write("            const nomeDoEvento = window.document.getElementById('nomeDoevento');\n");
      out.write("            const local = document.getElementById('local');\n");
      out.write("            const endereco = document.getElementById('endereco');\n");
      out.write("            const cep = document.getElementById('cep');\n");
      out.write("            var regNomeDoEvento = new RegExp(\"[A-z]{6,30}\");\n");
      out.write("            var regLocal = new RegExp(\"[a-zA-Z0-9\\s.,-]+$\");\n");
      out.write("            var regCep = new RegExp(\"^[0-9]{8}$\");\n");
      out.write("\n");
      out.write("\n");
      out.write("            //função para validar dados do evento\n");
      out.write("            function cadastrarEvento() {\n");
      out.write("                if (validarEvento()) {\n");
      out.write("                    return true;\n");
      out.write("                } else {\n");
      out.write("                    alert(\"Campo com erro\");\n");
      out.write("                    return false;\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            /* função para validar cliente*/\n");
      out.write("            function validarEvento() {\n");
      out.write("                if (regNomeDoEvento.test(nomeDoEvento.value) && regLocal.test(local.value) && regLocal.test(endereco.value) && regCep.test(cep.value)) {\n");
      out.write("                    return true;\n");
      out.write("                } else {\n");
      out.write("                    return false;\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("\n");
      out.write("        </script>\n");
      out.write("        <footer>\n");
      out.write("            <!--links-->\n");
      out.write("            <a class=\"link\">termo de uso</a>\n");
      out.write("            <a class=\"link\">Política de privacidade</a>\n");
      out.write("            <a class=\"link\">Política de reembolso</a>\n");
      out.write("            <!--logo em rodape-->\n");
      out.write("            <a href=\"");
      out.print(emailIndex);
      out.write("\" class=\"logo-rodape\"> Diver<br />Ticket<br /></a>\n");
      out.write("            <a class=\"link\">Perguntas Frequente</a>\n");
      out.write("            <a class=\"link\">Informação de contatos</a>\n");
      out.write("            <a class=\"link\">Sobre Nos</a>\n");
      out.write("        </footer>\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
