/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.100
 * Generated at: 2024-06-04 00:25:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public final class eventos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(5);
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"styleEventos.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"styleCards.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"styleBtnLogin.css\">\n");
      out.write("        <title>Eventos</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <!-- ==========================================cabeçalho========================================== -->\n");
      out.write("        ");

            // recebe dados do usuario
            String u = null;
            u = request.getParameter("email");
            String emailIndex = "index.jsp?email=" + u;
            String emailEvento = "cadastroEvento.jsp?email=" + u;
            String emailMeusIngressos = "meusIngressos.jsp?email=" + u;
            String emailMeusEventos = "meuEvento.jsp?email=" + u;

        
      out.write("\n");
      out.write("        <header>\n");
      out.write("            <!--logo-->\n");
      out.write("            <a href=\"");
      out.print( emailIndex);
      out.write("\"  class=\"logo\"> Diver<br />Ticket<br /></a>\n");
      out.write("            <!--botoes header-->\n");
      out.write("            <nav>\n");
      out.write("                ");

                    String emailPerfil = "meuPerfil.jsp?email=" + u;

                    // if para saber se o email que veio da outra pagina não esta null
                    // se tiver td certo mostra as opção de usuario logado
                    if (u != null) {
                        int a = u.indexOf("@");
                        String nome = u.substring(0, a);
                
      out.write("\n");
      out.write("                <div class=\"dropdown\">\n");
      out.write("                    <button onclick=\"myFunction()\" class=\"dropbtn\"> ");
      out.print(nome);
      out.write(" </button>\n");
      out.write("                    <div id=\"myDropdown\" class=\"dropdown-content\">\n");
      out.write("                        <a href= \"");
      out.print(emailPerfil);
      out.write("\">Perfil</a>\n");
      out.write("                        <a href=\"");
      out.print(emailMeusIngressos);
      out.write("\">Meus Ingresso</a>\n");
      out.write("                        <a href=\"");
      out.print(emailMeusEventos);
      out.write("\">Meus eventos</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <a href=\"");
      out.print(emailEvento);
      out.write("\"<button class=\"button button2\">Criar Eventos</button></a>\n");
      out.write("\n");
      out.write("                ");

                    // se não mostra a opção sem esta logado
                } else {
                
      out.write("\n");
      out.write("\n");
      out.write("                <a href=\"loginUsuario.html\"><button class=\"button button1\">Login</button></a>\n");
      out.write("                ");

                    }
                
      out.write("\n");
      out.write("            </nav>\n");
      out.write("            <!-- ==================================script dropdoow=================================================== -->\n");
      out.write("            <script>\n");
      out.write("                /* Quando o usuário clicar no botão, alterne entre ocultar e mostrar o conteúdo do menu suspenso */\n");
      out.write("                function myFunction() {\n");
      out.write("                    document.getElementById(\"myDropdown\").classList.toggle(\"show\");\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                // Feche o menu suspenso se o usuário clicar fora dele\n");
      out.write("                window.onclick = function (event) {\n");
      out.write("                    if (!event.target.matches('.dropbtn')) {\n");
      out.write("                        var dropdowns = document.getElementsByClassName(\"dropdown-content\");\n");
      out.write("                        var i;\n");
      out.write("                        for (i = 0; i < dropdowns.length; i++) {\n");
      out.write("                            var openDropdown = dropdowns[i];\n");
      out.write("                            if (openDropdown.classList.contains('show')) {\n");
      out.write("                                openDropdown.classList.remove('show');\n");
      out.write("                            }\n");
      out.write("                        }\n");
      out.write("                    }\n");
      out.write("                };\n");
      out.write("            </script>\n");
      out.write("        </header>\n");
      out.write("        <!-- ========================================================================================================================= -->\n");
      out.write("        <!-- ==========================================menu============================================= -->\n");
      out.write("        <section class=\"menu\">\n");
      out.write("            <div>\n");
      out.write("                <input type=\"text\" placeholder=\"Pesquisar eventos,show,teatro...\" title=\"Type in a name\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <nav class=\"sub-menu\">\n");
      out.write("                <a href=\"cadastroUsuario.html\" class=\"link\">Cadastre-se</a>\n");
      out.write("                <a class=\"link\">Contato</a>\n");
      out.write("                <a class=\"link\">Ajuda</a>\n");
      out.write("            </nav>\n");
      out.write("        </section>\n");
      out.write("        <!-- =====================================================main=========================================================== -->\n");
      out.write("        <h2> Eventos</h2>\n");
      out.write("\n");
      out.write("        <main>\n");
      out.write("\n");
      out.write("\n");
      out.write("            ");

                //  conectar com banco de dados
                try {
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/diver", "root", "p@$$w0rd");
                    // busca todos os evento no banco de dados
                    PreparedStatement st = conectado.prepareStatement("select id_evento ,data_inicio,nomeDoevento,imagem from evento");
                    ResultSet resultado = st.executeQuery();//executa o select(busca)

                    // mostra todos os evento que estão no banco de dados
                    while (resultado.next()) {
                        String evento = "eventoExpecifico.jsp?idEvento=" + resultado.getInt("id_evento");

            
      out.write("\n");
      out.write("\n");
      out.write("            <!--card eventos-->\n");
      out.write("            <div class=\"img-cards\">\n");
      out.write("                <a href=\"");
      out.print(evento);
      out.write("\">\n");
      out.write("                    <img src=\"imgs/");
      out.print(resultado.getString("imagem"));
      out.write("\" >\n");
      out.write("                </a>\n");
      out.write("                <div class=\"desc\">\n");
      out.write("                    <h3>");
      out.print(resultado.getString("data_inicio"));
      out.write("</h3>\n");
      out.write("                    <h5> ");
      out.print(resultado.getString("nomeDoEvento"));
      out.write(" </h5>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            ");


                    }
                } catch (ClassNotFoundException ex) {
                    out.print(ex);

                } catch (SQLException ex) {
                    out.print(ex);

                }
            
      out.write("\n");
      out.write("\n");
      out.write("        </main>\n");
      out.write("        <!-- =============================================================================================================== -->\n");
      out.write("        <!--footer-->\n");
      out.write("        <footer>\n");
      out.write("            <!--links-->\n");
      out.write("            <a class=\"link\">termo de uso</a>\n");
      out.write("            <a class=\"link\">Política de privacidade</a>\n");
      out.write("            <a class=\"link\">Política de reembolso</a>\n");
      out.write("            <!--logo em rodape-->\n");
      out.write("            <a href=\"");
      out.print( emailIndex);
      out.write("\" class=\"logo-rodape\"> Diver<br />Ticket<br /></a>\n");
      out.write("            <a class=\"link\">Perguntas Frequente</a>\n");
      out.write("            <a class=\"link\">Informação de contatos</a>\n");
      out.write("            <a class=\"link\">Sobre Nos</a>\n");
      out.write("        </footer>\n");
      out.write("        <!-- =============================================================================================================== -->\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
