/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.100
 * Generated at: 2024-06-03 21:36:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"pt-BR\">\n");
      out.write("\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <meta name=\"description\"\n");
      out.write("              content=\"A Diver ticket é a plataforma online de eventos. Shows, festas, teatros, stand up, cursos e muito mais. Encontre e organize eventos com a Diver Ticket!\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"style.css\" type=\"text/css\" media=\"screen\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"styleSlide.css\" type=\"text/css\" media=\"screen\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"styleCards.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"styleBtnLogin.css\">\n");
      out.write("        <title>Diver tickt</title>\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <!-- ==========================================cabeçalho========================================== -->\n");
      out.write("    <header>\n");
      out.write("        <!--logo-->\n");
      out.write("        <a class=\"logo\"> Diver<br />Ticket<br /></a>\n");
      out.write("        <!--botoes header-->\n");
      out.write("        <nav>\n");
      out.write("            ");

                String u = null;
                u = request.getParameter("email");
                String emailCriarEvento = "cadastroEvento.jsp?email=" + u;
                String emailEvento = "eventos.jsp?email=" + u;
                String emailPerfil = "meuPerfil.jsp?email=" + u;
                String emailIngressos = "meusIngressos.jsp?email=" + u;
                String emailMeusEventos = "meuEvento.jsp?email=" + u;

                // se o usuario estiver logado abrira opções de usuario logado
                if (u != null) {
                    int a = u.indexOf("@");
                    String nome = u.substring(0, a);
            
      out.write("\n");
      out.write("            <div class=\"dropdown\">\n");
      out.write("                <button onclick=\"myFunction()\" class=\"dropbtn\"> ");
      out.print( nome);
      out.write(" </button>\n");
      out.write("                <div id=\"myDropdown\" class=\"dropdown-content\">\n");
      out.write("                    <a href= \"");
      out.print(emailPerfil);
      out.write("\">Perfil</a>\n");
      out.write("                    <a href=\"");
      out.print(emailIngressos);
      out.write("\">Meus Ingresso</a>\n");
      out.write("                    <a href=\"");
      out.print(emailMeusEventos);
      out.write("\">Meus eventos</a>\n");
      out.write("                    <a href=\"index.jsp\">Sair</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <a href=\"");
      out.print(emailCriarEvento);
      out.write("\"><button class=\"button button2\">Criar Eventos</button></a>\n");
      out.write("\n");
      out.write("            ");
 // se não aparecera as opções de não logado
            } else {
            
      out.write("\n");
      out.write("\n");
      out.write("            <a href=\"loginUsuario.html\"><button class=\"button button1\">Login</button></a>\n");
      out.write("            ");

                }
            
      out.write("\n");
      out.write("        </nav>\n");
      out.write("    </header>\n");
      out.write("    <!-- ==================================script dropdoow=================================================== -->\n");
      out.write("    <script>\n");
      out.write("        /* Quando o usuário clicar no botão, alterne entre ocultar e mostrar o conteúdo do menu suspenso */\n");
      out.write("        function myFunction() {\n");
      out.write("            document.getElementById(\"myDropdown\").classList.toggle(\"show\");\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        // Feche o menu suspenso se o usuário clicar fora dele\n");
      out.write("        window.onclick = function (event) {\n");
      out.write("            if (!event.target.matches('.dropbtn')) {\n");
      out.write("                var dropdowns = document.getElementsByClassName(\"dropdown-content\");\n");
      out.write("                var i;\n");
      out.write("                for (i = 0; i < dropdowns.length; i++) {\n");
      out.write("                    var openDropdown = dropdowns[i];\n");
      out.write("                    if (openDropdown.classList.contains('show')) {\n");
      out.write("                        openDropdown.classList.remove('show');\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("    <!-- ==========================================menu============================================= -->\n");
      out.write("    <section class=\"menu\">\n");
      out.write("        <div>\n");
      out.write("            <input type=\"text\" placeholder=\"Pesquisar eventos,show,teatro...\" title=\"Type in a name\">\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <nav class=\"sub-menu\">\n");
      out.write("            <a href=\"");
      out.print( emailEvento);
      out.write("\" class=\"link\">Eventos</a>\n");
      out.write("            <a href=\"cadastroUsuario.html\" class=\"link\">Cadastre-se</a>\n");
      out.write("            <a class=\"link\">Contato</a>\n");
      out.write("            <a class=\"link\">Ajuda</a>\n");
      out.write("        </nav>\n");
      out.write("    </section>\n");
      out.write("    <!-- ========================================================================================================================= -->\n");
      out.write("    <main class=\"main\">\n");
      out.write("\n");
      out.write("        <!-- ====================================================slide==================================================================== -->\n");
      out.write("        <div class=\"slide\">\n");
      out.write("\n");
      out.write("\n");
      out.write("            <div class=\"todoSlides desaparecem\">\n");
      out.write("\n");
      out.write("                <img class=\"img-slide\" src=\"imgs/Black And White Illustrated Music Festival Facebook Cover.png\">\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"todoSlides desaparecem\">\n");
      out.write("\n");
      out.write("                <img class=\"img-slide\" src=\"imgs/daniel.png\">\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"todoSlides desaparecem\">\n");
      out.write("\n");
      out.write("                <img class=\"img-slide\" src=\"imgs/thiaguinho.jpg\">\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!-- Os pontos/círculos -->\n");
      out.write("        <div>\n");
      out.write("            <span class=\"pontos\" onclick=\"currentSlide(1)\"></span>\n");
      out.write("            <span class=\"pontos\" onclick=\"currentSlide(2)\"></span>\n");
      out.write("            <span class=\"pontos\" onclick=\"currentSlide(3)\"></span>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <script>// função para ficar trocando os slides na pagina principal\n");
      out.write("            let slideIndex = 0;\n");
      out.write("            showSlides();\n");
      out.write("\n");
      out.write("            function showSlides() {\n");
      out.write("                let i;\n");
      out.write("                let slides = document.getElementsByClassName(\"todoSlides\");\n");
      out.write("                let pontos = document.getElementsByClassName(\"pontos\");\n");
      out.write("                for (i = 0; i < slides.length; i++) {\n");
      out.write("                    slides[i].style.display = \"none\";\n");
      out.write("                }\n");
      out.write("                slideIndex++;\n");
      out.write("                if (slideIndex > slides.length) {\n");
      out.write("                    slideIndex = 1;\n");
      out.write("                }\n");
      out.write("                for (i = 0; i < pontos.length; i++) {\n");
      out.write("                    pontos[i].className = pontos[i].className.replace(\" active\", \"\");\n");
      out.write("                }\n");
      out.write("                slides[slideIndex - 1].style.display = \"block\";\n");
      out.write("                pontos[slideIndex - 1].className += \" active\";\n");
      out.write("                setTimeout(showSlides, 5000);\n");
      out.write("            }\n");
      out.write("        </script>\n");
      out.write("\n");
      out.write("        <!-- ========================================================================================================================= -->\n");
      out.write("\n");
      out.write("        <div class=\"conteudo\">\n");
      out.write("            <!-- =====================================================categoria=========================================================== -->\n");
      out.write("            <section class=\"categoria\">\n");
      out.write("                <div class=\"opcao-categoria\">\n");
      out.write("                    <a><img class=\"img\" src=\"imgs/show.png\"></a>\n");
      out.write("                    <a class=\"link\">Festa e show</a>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"opcao-categoria\">\n");
      out.write("                    <a><img class=\"img\" src=\"imgs/teatro.png\"></a>\n");
      out.write("                    <a class=\"link\">Teatro</a>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"opcao-categoria\">\n");
      out.write("                    <a><img class=\"img\" src=\"imgs/palestra.png\"></a>\n");
      out.write("\n");
      out.write("                    <a class=\"link\">Palestra</a>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"opcao-categoria\">\n");
      out.write("                    <a><img class=\"img\" src=\"imgs/stand.png\"></a>\n");
      out.write("\n");
      out.write("                    <a class=\"link\">Stand up comedy</a>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"opcao-categoria\">\n");
      out.write("                    <a><img class=\"img\" src=\"imgs/esporte.png\"></a>\n");
      out.write("\n");
      out.write("                    <a class=\"link\">Esporte</a>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"opcao-categoria\">\n");
      out.write("                    <a><img class=\"img\" src=\"imgs/gastrono.png\"></a>\n");
      out.write("\n");
      out.write("                    <a class=\"link\">Gastronomia</a>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"opcao-categoria\">\n");
      out.write("                    <a><img class=\"img\" src=\"imgs/passeio.png\"></a>\n");
      out.write("\n");
      out.write("                    <a class=\"link\">Passeios</a>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"opcao-categoria\">\n");
      out.write("                    <a><img class=\"img\" src=\"imgs/infantil.png\"></a>\n");
      out.write("\n");
      out.write("                    <a class=\"link\">Infantil</a>\n");
      out.write("                </div>\n");
      out.write("            </section>\n");
      out.write("\n");
      out.write("            <section>\n");
      out.write("                <!-- =============================================================================================================== -->\n");
      out.write("                <!-- =====================================================eventos=================================================== -->\n");
      out.write("                <!-- eventos principal-->\n");
      out.write("                <h2>Principais eventos</h2>\n");
      out.write("\n");
      out.write("                <nav class=\"eventos\">\n");
      out.write("                    <!-- card eventos principal 1-->\n");
      out.write("                    <div class=\"centralizar\">\n");
      out.write("                        <div class=\"img-cards\">\n");
      out.write("                            <a target=\"_blank\" href=\"https://www.sympla.com.br/evento/bh-stock-festival/2411037\">\n");
      out.write("                                <img src=\"imgs/Stock Festival.png\" alt=\"Cinque Terre\">\n");
      out.write("                            </a>\n");
      out.write("                            <div class=\"desc\">\n");
      out.write("                                <h3>15 a 18 de Agosto de 2024</h3>\n");
      out.write("                                <h5>Stock Festival</h5>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <!-- card eventos principal 2-->\n");
      out.write("                    <div class=\"centralizar\">\n");
      out.write("                        <div class=\"img-cards\">\n");
      out.write("                            <a target=\"_blank\"\n");
      out.write("                               href=\"https://www.sympla.com.br/evento/gravacao-dvd-lauana-prado-transcende/2409869\">\n");
      out.write("                                <img src=\"imgs/Luana Prado.png\" alt=\"Cinque Terre\">\n");
      out.write("                            </a>\n");
      out.write("                            <div class=\"desc\">\n");
      out.write("                                <h3>28 junho de 2024</h3>\n");
      out.write("                                <h5>Luana Prado</h5>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- card eventos principal 3-->\n");
      out.write("                    <div class=\"centralizar\">\n");
      out.write("                        <div class=\"img-cards\">\n");
      out.write("                            <a target=\"_blank\"\n");
      out.write("                               href=\"https://bileto.sympla.com.br/event/92547/d/247880?_gl=1*eg83m2*_ga*MzU4NDI5NjYzLjE3MTI4NTE4MTA.*_ga_KXH10SQTZF*MTcxMjg1MTgxMC4xLjEuMTcxMjg1NDkzMS42MC4wLjE4NDM5MDkyOTY.\">\n");
      out.write("                                <img src=\"imgs/matheusCeara.jpeg\" alt=\"Cinque Terre\">\n");
      out.write("                            </a>\n");
      out.write("                            <div class=\"desc\">\n");
      out.write("                                <h3> 29 e 30 de julho de 2024</h3>\n");
      out.write("                                <h5>Matheus Ceará</h5>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <!-- card eventos principal 4-->\n");
      out.write("                    <div class=\"centralizar\">\n");
      out.write("                        <div class=\"img-cards\">\n");
      out.write("                            <a target=\"_blank\" href=\"img_5terre.jpg\">\n");
      out.write("                                <img src=\"imgs/Lolla.png\" alt=\"Cinque Terre\">\n");
      out.write("                            </a>\n");
      out.write("                            <div class=\"desc\">\n");
      out.write("                                <h3>28, 29 e 30 de março de 2025</h3>\n");
      out.write("                                <h5>Lollapalooza Brasil 2025</h5>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <!-- card eventos principal 5-->\n");
      out.write("                    <div class=\"centralizar\">\n");
      out.write("                        <div class=\"img-cards\">\n");
      out.write("                            <a target=\"_blank\"\n");
      out.write("                               href=\"https://bileto.sympla.com.br/event/88243/d/223728?_gl=1*1nsn4xh*_ga*MzU4NDI5NjYzLjE3MTI4NTE4MTA.*_ga_KXH10SQTZF*MTcxMjg1MTgxMC4xLjEuMTcxMjg1NTAzMi4xOS4wLjE4NDM5MDkyOTY.\">\n");
      out.write("                                <img src=\"imgs/o maior show ilusionismo.webp\" alt=\"Cinque Terre\">\n");
      out.write("                            </a>\n");
      out.write("                            <div class=\"desc\">\n");
      out.write("                                <h3> 30 de maio de 2024</h3>\n");
      out.write("                                <h5>Maior show ilusionismo</h5>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                </nav>\n");
      out.write("                <!-- =============================================================================================================== -->\n");
      out.write("                <!--evento da semana-->\n");
      out.write("                <h2>Eventos da semana</h2>\n");
      out.write("\n");
      out.write("                <nav class=\"eventos\">\n");
      out.write("\n");
      out.write("                    <!-- card eventos da semana 1-->\n");
      out.write("                    <div class=\"centralizar\">\n");
      out.write("                        <div class=\"img-cards\">\n");
      out.write("                            <a target=\"_blank\" href=\"img_5terre.jpg\">\n");
      out.write("                                <img src=\"imgs/Monica.jpg\" alt=\"Cinque Terre\">\n");
      out.write("                            </a>\n");
      out.write("                            <div class=\"desc\">\n");
      out.write("                                <h3>28, 29 e 30 de agosto de 2024</h3>\n");
      out.write("                                <h5>Talk com MONI</h5>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <!-- card eventos da semana 2-->\n");
      out.write("                    <div class=\"centralizar\">\n");
      out.write("                        <div class=\"img-cards\">\n");
      out.write("                            <a target=\"_blank\"\n");
      out.write("                               href=\"https://bileto.sympla.com.br/event/92614/d/248167?_gl=1*12idwc4*_ga*MzU4NDI5NjYzLjE3MTI4NTE4MTA.*_ga_KXH10SQTZF*MTcxMjg1MTgxMC4xLjEuMTcxMjg1NTE5OS41Ny4wLjE4NDM5MDkyOTY.\">\n");
      out.write("                                <img src=\"imgs/o que so sabemos juntos.jpeg\" alt=\"Cinque Terre\">\n");
      out.write("                            </a>\n");
      out.write("                            <div class=\"desc\">\n");
      out.write("                                <h3>8, 9 e 10 de junho de 2024</h3>\n");
      out.write("                                <h5>Oque só sabemos juntos</h5>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <!-- card eventos da semana 3-->\n");
      out.write("                    <div class=\"centralizar\">\n");
      out.write("                        <div class=\"img-cards\">\n");
      out.write("                            <a target=\"_blank\"\n");
      out.write("                               href=\"https://bileto.sympla.com.br/event/90561?_gl=1*of8j6t*_ga*MzU4NDI5NjYzLjE3MTI4NTE4MTA.*_ga_KXH10SQTZF*MTcxMjg1MTgxMC4xLjEuMTcxMjg1NTM2Ny42MC4wLjE4NDM5MDkyOTY.\">\n");
      out.write("                                <img src=\"imgs/reclamacaododia.jpeg\" alt=\"Cinque Terre\">\n");
      out.write("                            </a>\n");
      out.write("                            <div class=\"desc\">\n");
      out.write("                                <h3>24, 25 e 36 de maio de 2024</h3>\n");
      out.write("                                <h5>Reclamação do dia</h5>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <!-- card eventos da semana 4-->\n");
      out.write("                    <div class=\"centralizar\">\n");
      out.write("                        <div class=\"img-cards\">\n");
      out.write("                            <a target=\"_blank\" href=\"https://www.sympla.com.br/evento/os-tres-porquinhos-twp/2410228\">\n");
      out.write("                                <img src=\"imgs/tres porquinho.jpg\" alt=\"Cinque Terre\">\n");
      out.write("                            </a>\n");
      out.write("                            <div class=\"desc\">\n");
      out.write("                                <h3>28, 29 e 30 de agosto de 2025</h3>\n");
      out.write("                                <h5>Tres Porquinhos</h5>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <!-- card eventos da semana 5-->\n");
      out.write("                    <div class=\"centralizar\">\n");
      out.write("                        <div class=\"img-cards\">\n");
      out.write("                            <a target=\"_blank\"\n");
      out.write("                               href=\"https://bileto.sympla.com.br/event/90122/d/234053?_gl=1*73p5q2*_ga*MzU4NDI5NjYzLjE3MTI4NTE4MTA.*_ga_KXH10SQTZF*MTcxMjg1MTgxMC4xLjEuMTcxMjg1NTUxOS41My4wLjE4NDM5MDkyOTY.\">\n");
      out.write("                                <img src=\"imgs/teatro222show.jpg\" alt=\"Cinque Terre\">\n");
      out.write("                            </a>\n");
      out.write("                            <div class=\"desc\">\n");
      out.write("                                <h3>21, 22 e 23 de março de 2024</h3>\n");
      out.write("                                <h5>Barbara</h5>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </nav>\n");
      out.write("                <!-- =============================================================================================================== -->\n");
      out.write("                <!-- eventos em 24hrs-->\n");
      out.write("                <h2>Eventos em 24Hrs</h2>\n");
      out.write("\n");
      out.write("                <nav class=\"eventos\">\n");
      out.write("\n");
      out.write("                    <!-- card eventos em 24hrs 1-->\n");
      out.write("                    <div class=\"centralizar\">\n");
      out.write("                        <div class=\"img-cards\">\n");
      out.write("                            <a target=\"_blank\" href=\"https://www.sympla.com.br/evento/14-trilhao-de-curvelo/2388822\">\n");
      out.write("                                <img src=\"imgs/trilha.png\" alt=\"Cinque Terre\">\n");
      out.write("                            </a>\n");
      out.write("                            <div class=\"desc\">\n");
      out.write("                                <h3>28, 29 e 30 de setembro de 2025</h3>\n");
      out.write("                                <h5>Festival da montanha</h5>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <!-- card eventos em 24hrs 2-->\n");
      out.write("                    <div class=\"centralizar\">\n");
      out.write("                        <div class=\"img-cards\">\n");
      out.write("                            <a target=\"_blank\"\n");
      out.write("                               href=\"https://bileto.sympla.com.br/event/66707/d/249259/s/1700278?_gl=1*zgxkkw*_ga*MzU4NDI5NjYzLjE3MTI4NTE4MTA.*_ga_KXH10SQTZF*MTcxMjg1MTgxMC4xLjEuMTcxMjg1NTkyNy40Ny4wLjE4NDM5MDkyOTY.\">\n");
      out.write("                                <img src=\"imgs/uma aventura na neve.jpeg\" alt=\"Cinque Terre\">\n");
      out.write("                            </a>\n");
      out.write("                            <div class=\"desc\">\n");
      out.write("                                <h3>22, 23 e 24 de julho de 2024</h3>\n");
      out.write("                                <h5>Uma Aventura na Neve</h5>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <!-- card eventos em 24hrs 3-->\n");
      out.write("                    <div class=\"centralizar\">\n");
      out.write("                        <div class=\"img-cards\">\n");
      out.write("                            <a target=\"_blank\"\n");
      out.write("                               href=\"https://bileto.sympla.com.br/event/90376/d/235942?_gl=1*16ahi07*_ga*MzU4NDI5NjYzLjE3MTI4NTE4MTA.*_ga_KXH10SQTZF*MTcxMjg1MTgxMC4xLjEuMTcxMjg1NTk1NS4xOS4wLjE4NDM5MDkyOTY.\">\n");
      out.write("                                <img src=\"imgs/patati.webp\" alt=\"Cinque Terre\">\n");
      out.write("                            </a>\n");
      out.write("                            <div class=\"desc\">\n");
      out.write("                                <h3>28, 29 e 30 de agosto de 2025</h3>\n");
      out.write("                                <h5>Circo Patati Patatá</h5>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <!-- card eventos em 24hrs 4-->\n");
      out.write("                    <div class=\"centralizar\">\n");
      out.write("                        <div class=\"img-cards\">\n");
      out.write("                            <a target=\"_blank\" href=\"https://www.sympla.com.br/evento/a-domingueira-abril/2373745\">\n");
      out.write("                                <img src=\"imgs/domingueira.jpg\" alt=\"Cinque Terre\">\n");
      out.write("                            </a>\n");
      out.write("                            <div class=\"desc\">\n");
      out.write("                                <h3>Todos os domingos</h3>\n");
      out.write("                                <h5>Domingueira</h5>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <!-- card eventos em 24hrs 5-->\n");
      out.write("                    <div class=\"centralizar\">\n");
      out.write("                        <div class=\"img-cards\">\n");
      out.write("                            <a target=\"_blank\" href=\"img_5terre.jpg\">\n");
      out.write("                                <img src=\"imgs/festivaldamusica.png\" alt=\"Cinque Terre\">\n");
      out.write("                            </a>\n");
      out.write("                            <div class=\"desc\">\n");
      out.write("                                <h3>28, 29 e 30 de março de 2025</h3>\n");
      out.write("                                <h5>Festival Da Musica</h5>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                </nav>\n");
      out.write("                <!-- =============================================================================================================== -->\n");
      out.write("            </section>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </main>\n");
      out.write("    <!-- =============================================================================================================== -->\n");
      out.write("    <!--footer-->\n");
      out.write("    <footer>\n");
      out.write("        <!--links-->\n");
      out.write("        <a class=\"link\">termo de uso</a>\n");
      out.write("        <a class=\"link\">Política de privacidade</a>\n");
      out.write("        <a class=\"link\">Política de reembolso</a>\n");
      out.write("        <!--logo em rodape-->\n");
      out.write("        <a class=\"logo-rodape\"> Diver<br />Ticket<br /></a>\n");
      out.write("        <a class=\"link\">Perguntas Frequente</a>\n");
      out.write("        <a class=\"link\">Informação de contatos</a>\n");
      out.write("        <a class=\"link\">Sobre Nos</a>\n");
      out.write("    </footer>\n");
      out.write("    <!-- =============================================================================================================== -->\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
