/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.100
 * Generated at: 2024-06-03 23:31:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public final class meusIngressos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(5);
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"styleMeusIngressos.css\">\n");
      out.write("        <title>Meus Ingressos</title>\n");
      out.write("        <style>\n");
      out.write("\n");
      out.write("            main{\n");
      out.write("                display: flex;\n");
      out.write("                flex-direction: row;\n");
      out.write("                flex-wrap: wrap;\n");
      out.write("                justify-content:center;\n");
      out.write("                align-items: center;\n");
      out.write("                gap:30px;\n");
      out.write("                padding: 50px;\n");
      out.write("                margin: 20px;\n");
      out.write("\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .ticket {\n");
      out.write("                background-color: #f3f3f3;\n");
      out.write("                border: 2px dashed #d9d9d9;\n");
      out.write("                padding: 20px;\n");
      out.write("                max-width: 300px;\n");
      out.write("                margin: auto;\n");
      out.write("                text-align: center;\n");
      out.write("                font-family: Arial, sans-serif;\n");
      out.write("\n");
      out.write("\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .ticket h2 {\n");
      out.write("                margin-top: 0;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .ticket p {\n");
      out.write("                margin: 5px 0;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .ticket .barcode {\n");
      out.write("                height: 60px;\n");
      out.write("                margin: 20px 0;\n");
      out.write("                background-image: url('data:image/svg+xml;utf8,<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"100%\" height=\"100%\"><rect width=\"10%\" height=\"100%\"/><rect x=\"20%\" width=\"10%\" height=\"100%\"/><rect x=\"40%\" width=\"10%\" height=\"100%\"/><rect x=\"60%\" width=\"10%\" height=\"100%\"/><rect x=\"80%\" width=\"10%\" height=\"100%\"/></svg>');\n");
      out.write("                background-size: cover;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");
  
            String u = null;
            u = request.getParameter("email");
            String emailIndex = "index.jsp?email=" + u;

        
      out.write("\n");
      out.write("\n");
      out.write("        <!-- ==========================================cabeçalho========================================== -->\n");
      out.write("        <header>\n");
      out.write("            <!--logo-->\n");
      out.write("            <a href=\"");
      out.print( emailIndex);
      out.write("\" class=\"logo\"> Diver<br />Ticket<br /></a>\n");
      out.write("            <!--botoes header-->\n");
      out.write("        </header>\n");
      out.write("        <!-- ========================================================================================================================= -->\n");
      out.write("\n");
      out.write("        <!-- =====================================================main=========================================================== -->\n");
      out.write("        <main>\n");
      out.write("            ");
    //  conectar com banco de dados
                try {
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/diver", "root", "p@$$w0rd");
                    // busca os inggresso do usuario com a condição do email dele
                    PreparedStatement st = conectado.prepareStatement("SELECT ingresso.qtdIngresso, ingresso.tipo_ingresso, evento.nomeDoevento, evento.endereco, evento.data_inicio, evento.hora_inicio  FROM ingresso INNER JOIN evento ON ingresso.fk_evento = evento.id_evento where ingresso.email = ?");
                    st.setString(1, u);
                    ResultSet resultado = st.executeQuery();//executa o select(busca)

                    // se ele tiver ingresso mostrara tds seus ingressos
                    while (resultado.next()) {
                        String codigo = "562532545124845";
                        int ctd = resultado.getInt("qtdIngresso");

                        for (int i = 0; i < ctd; i++) {
            
      out.write("\n");
      out.write("\n");
      out.write("            <!--card ingresso-->\n");
      out.write("            <div class=\"ticket\">\n");
      out.write("                <h2>");
      out.print(resultado.getString("nomeDoevento"));
      out.write("</h2>\n");
      out.write("                <p>Data: ");
      out.print(resultado.getString("data_inicio"));
      out.write(" Hora: ");
      out.print(resultado.getString("hora_inicio"));
      out.write("</p>\n");
      out.write("                <p>Local: ");
      out.print(resultado.getString("endereco"));
      out.write("</p>\n");
      out.write("                <p>");
      out.print(u);
      out.write("</p>\n");
      out.write("                <p>Tipo Ingresso:");
      out.print(resultado.getString("tipo_ingresso"));
      out.write("</p>\n");
      out.write("                <div class=\"barcode\"></div>\n");
      out.write("                <p>Código do Ingresso: ");
      out.print( codigo);
      out.write("</p>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            ");
                    }
                    }
                } catch (ClassNotFoundException ex) {
                    out.print(ex);

                } catch (SQLException ex) {
                    out.print(ex);

                }
            
      out.write("\n");
      out.write("        </main>\n");
      out.write("        <!-- =============================================================================================================== -->\n");
      out.write("        <!--footer-->\n");
      out.write("        <footer>\n");
      out.write("            <!--links-->\n");
      out.write("            <a class=\"link\">termo de uso</a>\n");
      out.write("            <a class=\"link\">Política de privacidade</a>\n");
      out.write("            <a class=\"link\">Política de reembolso</a>\n");
      out.write("            <!--logo em rodape-->\n");
      out.write("            <a href=\"");
      out.print( emailIndex);
      out.write("\" class=\"logo-rodape\"> Diver<br />Ticket<br /></a>\n");
      out.write("            <a class=\"link\">Perguntas Frequente</a>\n");
      out.write("            <a class=\"link\">Informação de contatos</a>\n");
      out.write("            <a class=\"link\">Sobre Nos</a>\n");
      out.write("        </footer>\n");
      out.write("        <!-- =============================================================================================================== -->\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
