/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.100
 * Generated at: 2024-06-03 23:32:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public final class relatorio_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(5);
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"styleRelatorio.css\">\n");
      out.write("        <title>relatorio</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <h2>Relatorio</h2>\n");
      out.write("\n");
      out.write("        ");

            String u = request.getParameter("email");
            String emailIndex = "index.jsp?email=" + u;

            // conecta com banco de dados
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/diver", "root", "p@$$w0rd");
                // busca todos os ingressos vendidos e informações dos usuarios que comprou
                PreparedStatement st = conectado.prepareStatement("SELECT ingresso.nome, ingresso.qtdIngresso, ingresso.valor_ingresso, ingresso.tipo_ingresso, evento.nomeDoevento FROM ingresso INNER JOIN evento ON ingresso.fk_evento = evento.id_evento  where evento.email = ? ");
                st.setString(1, u);
                ResultSet resultado = st.executeQuery();

        
      out.write("\n");
      out.write("\n");
      out.write("        <table id=\"tabelaIngressos\">\n");
      out.write("\n");
      out.write("            <tr>\n");
      out.write("                <th>Nome do Evento</th>\n");
      out.write("                <th>Nome do Cliente</th>\n");
      out.write("                <th>Quantidade de Ingressos</th>\n");
      out.write("                <th>Valor Total da Compra</th>\n");
      out.write("                <th>Tipo de Ingresso</th>\n");
      out.write("            </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("            ");
   int totalIngresso = 0;
                double valorTotal = 0;
                int qtdUsuario = 0, qtdEvento = 0;
                int qtdVip = 0, qtdMeia = 0, qtdInteira = 0;

                // exibi tds informaçoes do usuario
                while (resultado.next()) {

                    String nomeDoevento = resultado.getString("nomeDoevento");
                    String nomeUsuario = resultado.getString("nome");
                    int qtdIngresso = resultado.getInt("qtdIngresso");
                    double valorIngresso = resultado.getDouble("valor_ingresso");
                    String tipoIngresso = resultado.getString("tipo_ingresso");

                    totalIngresso += qtdIngresso;
                    valorTotal += valorIngresso;
                    qtdUsuario++;

                    if (tipoIngresso.equalsIgnoreCase("vip")) {
                        qtdVip += 1 * qtdIngresso;

                    }

                    if (tipoIngresso.equalsIgnoreCase("meia")) {
                        qtdMeia += 1 * qtdIngresso;
                    }

                    if (tipoIngresso.equalsIgnoreCase("inteira")) {
                        qtdInteira += 1 * qtdIngresso;
                    }

            
      out.write("\n");
      out.write("\n");
      out.write("            <tr>\n");
      out.write("                <td>");
      out.print(nomeDoevento);
      out.write("</td>\n");
      out.write("                <td>");
      out.print(nomeUsuario);
      out.write("</td>\n");
      out.write("                <td>");
      out.print(qtdIngresso);
      out.write("</td>\n");
      out.write("                <td>");
      out.print(valorIngresso);
      out.write("</td>\n");
      out.write("                <td>");
      out.print(tipoIngresso);
      out.write("</td>\n");
      out.write("            </tr>\n");
      out.write("\n");
      out.write("            ");

                }// mostra os total 
            
      out.write("\n");
      out.write("            <tr>\n");
      out.write("                <td></td>\n");
      out.write("                <td>total cliente: ");
      out.print( qtdUsuario);
      out.write("</td>\n");
      out.write("                <td>total ingresso: ");
      out.print( totalIngresso);
      out.write(" </td>\n");
      out.write("                <td>valor total: ");
      out.print( valorTotal);
      out.write(" </td>\n");
      out.write("                <td>total vip: ");
      out.print( qtdVip);
      out.write("   total inteiro: ");
      out.print( qtdInteira);
      out.write("  total meia: ");
      out.print( qtdMeia);
      out.write("</td>\n");
      out.write("            </tr>\n");
      out.write("        </table>\n");
      out.write("\n");
      out.write("        ");
      } catch (ClassNotFoundException ex) {
                out.println(ex);
            } catch (SQLException ex) {
                out.println(ex);
            }
        
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
